# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = 'c8cf08e9af91bdc3e40d3e07569989c8'
  config.secret_key = '23659707b936e2967c43d5532f952128'
  config.default_from = 'gauravgulati9c@gmail.com'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end

ActionMailer::Base.delivery_method = :mailjet
ActionMailer::Base.default charset: "utf-8"
