# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a74aaa76da671d97445483884c736f388d00012e5dfc7461afea10f019e6c11824ef15d4cc9bb2a551bb92348ae773385d3ee317c82a5596fe078266c8ffb9d

test:
  secret_key_base: 3fb3a26640d0a86ef8aa8919376c870c1dad157ffef638aadf636007e8693d7d1fd360d63cb3408f1d08565fd6d87b2a8f5379a357852e576ac690fb7e81a720

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
